### PR TITLE
Fix errors import

### PR DESCRIPTION
**Pull request by grushetsky**
This removes a separate module for errors in order to fix the regression (#48).

I didn't manage to configure `prepublish` so that it would include _errors.js_ into the _dist_. @ericelliott, do you know how to do that using this tool?

### CODE REVIEW

**Comment by ericelliott** [comment]
Check out [how we made it work for RITEway](https://github.com/ericelliott/riteway/blob/master/source/index.js) with `esm`.

**Comment by grushetsky** [comment]
@ericelliott, `esm` has been added as you suggested. This approach was tested in a demo app using webpack (via [Create React App](https://github.com/facebook/create-react-app)) and it works properly.

But I wasn't able to make it work with [Parcel](https://parceljs.org). It issues an error:

image

@ericelliott, shall we neglect it for now? ⬆️

**Comment by ericelliott** [comment]
Did you report that to [the ESM repo](https://github.com/standard-things/esm) or [parcel](https://github.com/parcel-bundler/parcel)?

**Comment by grushetsky** [comment]
@ericelliott, it looks like I linked local `autodux` package in the wrong way when tried it the first time.

[This sample project](https://gist.github.com/grushetsky/2468944ccf80044e89f5706bbe39578e) with the correct `autodux` dependency in [_package.json_](https://gist.github.com/grushetsky/2468944ccf80044e89f5706bbe39578e#file-package-json-L10) works:

image

**Comment by ericelliott** [comment]
Do we still need the babel stuff?

**Comment by grushetsky** [comment]
We don't really need it! `node -r esm` can be used for tests. Thanks! 👍

**Comment by ericelliott** [comment]
Nice work. =)

**Comment by grushetsky** [comment]
Thank you. 🙂

**Pull request merged**
